<a href="https://colab.research.google.com/github/jcatillo/machine_learning/blob/main/matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Using numpy

In [4]:
import numpy as np
import torch

In [21]:
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# np.matmul(A,B) == A@B
print(np.round(A@B , 2))
print()
print(np.round(C.T@A , 2))

[[-0.25 -6.71 -1.64  0.75 -0.88]
 [-1.42 -1.62 -2.45  1.8   0.06]
 [ 1.9   9.27  5.24 -4.16 -0.38]]

[[ 0.92 -0.82 -1.27 -1.66]
 [-4.32  1.93  3.39  8.84]
 [ 0.29  0.64  0.06  1.87]
 [ 1.87 -0.82 -1.51 -3.56]
 [-0.43  1.14  1.26  1.72]
 [ 1.95 -0.37 -1.27 -2.67]
 [-1.27  1.12  1.55  3.02]]


Using pytorch

In [29]:
A = torch.randn(3,4)
B = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1, dtype=torch.float )

# np.matmul(A,B) == A@B
print(np.round(A@B , 2))
print()
print(np.round(A@C1 , 2))
print(np.round(A@C2 , 2))

tensor([[-0.7300,  1.7700, -0.5100, -2.4700, -4.4200],
        [ 0.7100, -1.0400,  0.3800,  2.0000,  3.2400],
        [-3.8500,  3.2700, -1.0700,  3.1500,  1.8200]])

tensor([[-3.7200,  0.0200,  3.2000,  0.6000,  1.4900,  3.3400, -1.4000],
        [ 2.7100, -0.0900, -2.6600, -0.4500, -0.9900, -2.5500,  0.8100],
        [ 3.2700, -2.0900, -4.1000, -2.0600,  1.1100, -0.8600, -1.7600]],
       dtype=torch.float64)
tensor([[-3.7200,  0.0200,  3.2000,  0.6000,  1.4900,  3.3400, -1.4000],
        [ 2.7100, -0.0900, -2.6600, -0.4500, -0.9900, -2.5500,  0.8100],
        [ 3.2700, -2.0900, -4.1000, -2.0600,  1.1100, -0.8600, -1.7600]])


/tmp/ipython-input-2109409815.py:9: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  print(np.round(A@C1 , 2))
