<a href="https://colab.research.google.com/github/jcatillo/machine_learning/blob/main/transposr_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

nv = np.array([ [1,2,3,4] ])
print(nv)
print()

print(nv.T)
print()

nvT = nv.T
print(nvT.T)

[[1 2 3 4]]

[[1]
 [2]
 [3]
 [4]]

[[1 2 3 4]]


In [12]:
nM = np.array([ [1,2,3,4],
                [5,6,7,8] ])
print(nM)
print()

print(nM.T)
print()

nMT = nM.T
print(nMT.T)


[[1 2 3 4]
 [5 6 7 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
#Using pyTorch
import torch

tv = torch.tensor([[1,2,3,4]])
print(tv)
print()

print(tv.T)
print()

tvT = tv.T
print(tvT.T)


tensor([[1, 2, 3, 4]])

tensor([[1],
        [2],
        [3],
        [4]])

tensor([[1, 2, 3, 4]])


In [17]:
tM = torch.tensor([ [1,2,3,4],
                    [5,6,7,8] ])

print(tM)
print()

print(tM.T)
print()

tMT = tM.T
print(tMT.T)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [18]:
print(f'Variable nv is of type {type(nv)}')
print(f'Variable nM is of type {type(nM)}')
print(f'Variable tv is of type {type(tv)}')
print(f'Variable tM is of type {type(tM)}')

Variable nv is of type <class 'numpy.ndarray'>
Variable nM is of type <class 'numpy.ndarray'>
Variable tv is of type <class 'torch.Tensor'>
Variable tM is of type <class 'torch.Tensor'>
